services:
  postgres:
    image: postgres:16
    container_name: snus-postgres
    restart: always
    environment:
      POSTGRES_USER: snus
      POSTGRES_PASSWORD: snuspassword
      POSTGRES_DB: snusdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: